"use client";

import { useMemo } from "react";
import JsBarcode from "jsbarcode";
import { BARCODE_OPTIONS } from "@/constants/labels";

// Barcode rendering is isolated here, the same way the POS keeps its scanner
// in one component: the engine can be swapped without touching any label.
//
// SVG rather than canvas — a barcode has to stay crisp at whatever DPI the
// printer runs at, and a canvas bitmap scaled to a 30mm sticker is exactly
// how bars end up unreadable.

// EAN-13 is what the backend generates (CLAUDE.md rule 13). Anything else
// that reaches here — a SKU standing in for a missing barcode — is drawn as
// CODE128, which encodes arbitrary text.
const EAN13_PATTERN = /^\d{13}$/;

// The value is drawn into the SVG (and into the <text> under the bars), and
// the result is injected as markup, so nothing but plain code characters is
// allowed through. Every code the API generates is digits; this is the guard
// for anything that isn't.
const SAFE_CODE_PATTERN = /^[A-Za-z0-9._-]+$/;

const SVG_NS = "http://www.w3.org/2000/svg";

// One run of JsBarcode per distinct code, not per sticker: a print run is
// mostly the same handful of codes repeated, and 500 stickers would
// otherwise mean 500 identical renders.
const markupCache = new Map<string, string | null>();

function drawBarcode(value: string): string | null {
  if (!SAFE_CODE_PATTERN.test(value)) return null;

  const svg = document.createElementNS(SVG_NS, "svg");
  const options = {
    width: BARCODE_OPTIONS.barWidth,
    height: BARCODE_OPTIONS.barHeight,
    fontSize: BARCODE_OPTIONS.fontSize,
    textMargin: BARCODE_OPTIONS.textMargin,
    margin: BARCODE_OPTIONS.margin,
    // The digits under the bars are what a cashier types in when a label is
    // scuffed — the same fallback the POS lookup supports.
    displayValue: true,
    background: "#ffffff",
    lineColor: "#000000",
  };

  try {
    JsBarcode(svg, value, { format: EAN13_PATTERN.test(value) ? "EAN13" : "CODE128", ...options });
    // JsBarcode reports an invalid value by rendering nothing rather than by
    // throwing — e.g. 13 digits whose check digit doesn't add up.
    if (!svg.childNodes.length) {
      JsBarcode(svg, value, { format: "CODE128", ...options });
    }
  } catch {
    return null;
  }
  if (!svg.childNodes.length) return null;

  // JsBarcode sizes the SVG with fixed width/height attributes. Swapping
  // those for a viewBox lets one rendering scale to any label size while
  // keeping the bar proportions intact. Those attributes carry a unit
  // ("226px"), which a viewBox must not — it takes bare numbers.
  const width = Number.parseFloat(svg.getAttribute("width") ?? "");
  const height = Number.parseFloat(svg.getAttribute("height") ?? "");
  if (Number.isFinite(width) && Number.isFinite(height) && width > 0 && height > 0) {
    svg.setAttribute("viewBox", `0 0 ${width} ${height}`);
    svg.removeAttribute("width");
    svg.removeAttribute("height");
  }
  svg.setAttribute("preserveAspectRatio", "xMidYMid meet");

  return svg.outerHTML;
}

function getBarcodeMarkup(value: string): string | null {
  if (markupCache.has(value)) return markupCache.get(value) ?? null;
  const markup = drawBarcode(value);
  markupCache.set(value, markup);
  return markup;
}

export function BarcodeSvg({ value }: { value: string }) {
  // Drawing needs a real DOM, so it happens on the client only. The sheet is
  // never part of the first render (it appears once products are chosen), so
  // there is nothing to hydrate and no flash of an empty barcode.
  const markup = useMemo(() => (typeof document === "undefined" ? null : getBarcodeMarkup(value)), [value]);

  if (!markup) {
    // Nothing scannable to draw — print the code as text so the piece can
    // still be found by typing it in.
    return <span className="label-code-fallback">{value}</span>;
  }

  // Generated by JsBarcode from a value matched against SAFE_CODE_PATTERN
  // above, so there is no untrusted markup here.
  return <span className="label-code-svg" dangerouslySetInnerHTML={{ __html: markup }} />;
}
