import type { I18n } from "@/types/common";
import type { ChangeRequest } from "@/types/changeRequest";
import type { CategoryRef } from "@/types/category";
import type { ProductImageRef, Variant } from "@/types/variant";
import type { BARCODE_SOURCES } from "@/constants/barcode";
import type { PRODUCT_LOOKUP_KINDS, PRODUCT_PRINT_STATES } from "@/constants/product";

// Whether a piece carries our generated EAN-13 or the supplier's own code
// (see constants/barcode.ts). Stored, never inferred from the code itself.
export type BarcodeSource = (typeof BARCODE_SOURCES)[number];

// One note the product carries on one option value. Translatable like every
// other piece of user-facing content (CLAUDE.md rule 9), falling back to the
// default language.
export interface ProductOptionValueNote {
  optionValueId: string;
  note: I18n;
}

export interface ProductVariantTypeRef {
  id: string;
  name: I18n;
  slug: string;
}

// Full detail DTO (GET /api/products/:id), including all variants resolved.
export interface Product {
  id: string;
  productNumber: number;
  name: I18n;
  slug: string;
  description: I18n | null;
  category: CategoryRef | null;
  basePrice: string;
  compareAtPrice: string | null;
  // Simple-product-only fields (CLAUDE.md: disabled once the product has variants).
  sku: string | null;
  // The code the POS matches a scan against. Generated by us by default, or
  // the supplier's own when `barcodeSource` says SUPPLIER — including on a
  // product WITH variants, where a single supplier code covering every size
  // sits on the parent and opens the variant picker when scanned.
  barcode: string | null;
  barcodeSource: BarcodeSource;
  stock?: number;
  isActive: boolean;
  // Opt-in low-stock alerts: only flagged products are measured against
  // Setting.lowStockThreshold (inventory low-stock view + dashboard count).
  // Off by default, since most products are one-off pieces with stock = 1.
  trackLowStock: boolean;
  // Numbered product (spec.md "Numbered shawls"): one photo carrying numbers,
  // each number a piece of its own. An explicit choice made when the product
  // is added, never inferred from which variant types it happens to use — it
  // decides what the rest of the product form shows, and which variant types
  // the API accepts (numbers only when true, never when false).
  isNumbered: boolean;
  // The colour of the numbers drawn on this product's photo, and of the badge
  // behind them (spec.md "Numbered shawls") — one pair for all of its points,
  // never one per point. Null means "follow the photo": the suggestion
  // resolvePointColors() reads from the primary image's brightness. A chosen
  // colour is kept even when the photograph is replaced, which is the whole
  // reason it is stored rather than derived every time.
  pointTextColor: string | null;
  pointBackgroundColor: string | null;
  // When this product's barcode labels were last printed (CLAUDE.md rule 13).
  // Null means never printed; reprinting simply moves the timestamp forward,
  // it is never a lock.
  labelsPrintedAt: string | null;

  // --- quick sell (spec.md "Quick sell") ---
  // When this piece was rung up at the counter before it existed in the
  // catalogue. Non-null is what makes the gaps below deliberate rather than
  // broken: no category, no cost, no barcode anybody chose, no photographs.
  quickSoldAt: string | null;
  // When a reviewer filled the rest in, or ruled it a one-off that will not
  // come back. Either way the SALE is untouched — the order lines are
  // snapshots, and money changed hands before any of this.
  completedAt: string | null;
  oneOffAt: string | null;
  // Sold, and still waiting for somebody to finish it off. Resolved on the
  // backend from the three stamps above so that every screen asks the same
  // question the same way — the products list marks these, and the "needs
  // completing" filter lists exactly them.
  needsCompleting: boolean;
  deletedAt: string | null;
  hasVariants: boolean;
  // Every note this product carries on an option value, keyed by the value
  // (spec.md "Notes on a product's options"). The same notes reach the
  // screens that DISPLAY a value through `variants[].values[].note`; this
  // flat list is what the product form edits, since it needs them before any
  // variant has been generated. Empty when the product has none.
  optionValueNotes: ProductOptionValueNote[];
  images: ProductImageRef[];
  variantTypes: ProductVariantTypeRef[];
  variants: Variant[];
  createdAt: string;
  updatedAt: string;
  // Everything still waiting for an Admin on this product, its variants or
  // its photos (spec.md "Employee change approvals"). Empty when nothing is
  // held. What makes an Employee's gated edit show as WAITING on the screen
  // they made it from, instead of looking as though it was thrown away.
  pendingChanges?: ChangeRequest[];
  // SENSITIVE (CLAUDE.md rule 19): Admin + Manager only — absent entirely
  // from Employee responses.
  cost?: string | null;
}

// Lighter list-view DTO (GET /api/products) — aggregate stock, variant count,
// no per-variant breakdown.
export interface ProductSummary {
  id: string;
  productNumber: number;
  name: I18n;
  slug: string;
  category: CategoryRef | null;
  basePrice: string;
  compareAtPrice: string | null;
  sku: string | null;
  barcode: string | null;
  barcodeSource: BarcodeSource;
  stock: number;
  isActive: boolean;
  trackLowStock: boolean;
  // Null until this product's labels have been printed at least once — what
  // the "not printed yet" list filter keys off.
  labelsPrintedAt: string | null;

  // --- quick sell (spec.md "Quick sell") ---
  // When this piece was rung up at the counter before it existed in the
  // catalogue. Non-null is what makes the gaps below deliberate rather than
  // broken: no category, no cost, no barcode anybody chose, no photographs.
  quickSoldAt: string | null;
  // When a reviewer filled the rest in, or ruled it a one-off that will not
  // come back. Either way the SALE is untouched — the order lines are
  // snapshots, and money changed hands before any of this.
  completedAt: string | null;
  oneOffAt: string | null;
  // Sold, and still waiting for somebody to finish it off. Resolved on the
  // backend from the three stamps above so that every screen asks the same
  // question the same way — the products list marks these, and the "needs
  // completing" filter lists exactly them.
  needsCompleting: boolean;

  // Whether this product owes a label at all. False once every code it would
  // print is the supplier's own — the garment already carries a physical
  // barcode, so there is nothing to stick on it. Resolved on the backend
  // because it depends on the variants, which a list row does not carry; the
  // "not printed yet" filter excludes the same products (never by faking
  // labelsPrintedAt, which would record a print that never happened).
  needsLabel: boolean;
  hasVariants: boolean;
  variantCount: number;
  // Which kinds of choice this product's variants are made of ("sizes",
  // "colours"), empty for a simple product. Enough to say what a picker will
  // ask for without loading every variant — CLAUDE.md rule 2 means these are
  // references, so a renamed type shows through here on its own.
  variantTypes: ProductVariantTypeRef[];
  // Numbered products (spec.md "Numbered shawls"): the numbers themselves are
  // illegible on a list thumbnail, so the list UI labels the product type with
  // a badge instead. `isNumbered` is the product's own explicit flag;
  // `numberCount` is how many distinct numbers it offers.
  isNumbered: boolean;
  numberCount: number;
  image: ProductImageRef | null;
  createdAt: string;
  updatedAt: string;
  cost?: string | null;
}

export type ProductPrintState = (typeof PRODUCT_PRINT_STATES)[number];
export type ProductLookupKind = (typeof PRODUCT_LOOKUP_KINDS)[number];

// One number of a numbered shawl (spec.md "Numbered shawls") as the POS needs
// it to ask "which one?": the number as drawn on the image, what is left of
// it, and the variant id that has to be named to sell it.
export interface ProductNumberOption {
  // The variant behind this number — an order line MUST carry it; a sale on
  // the parent alone is refused (error.order.variant_required).
  variantId: string;
  variantNumber: number;
  // The variant's own label, e.g. "1" or "1 / أحمر" when the product also
  // has colours.
  name: I18n;
  // The Number option value itself (CLAUDE.md rule 2: referenced, never
  // copied — renaming it upstream shows through here).
  number: I18n;
  numberKey: string;
  // What this number means on this shawl (spec.md "Notes on a product's
  // options") — the same note the picker draws beside the number. Never drawn
  // on the photograph: the markers are tight already and text over a
  // photograph cannot be relied on to be readable.
  note: I18n | null;
  sku: string;
  barcode: string | null;
  resolvedPrice: string;
  stock: number;
  // False for a number that cannot be sold right now — nothing left in
  // stock, or the variant is hidden. The POS greys these out rather than
  // hiding them, so the cashier can see the number exists and is gone.
  available: boolean;
  // Where the number sits on the product image, percentage 0-100.
  imageX: number | null;
  imageY: number | null;
}

// GET /api/products/lookup?code=… — what a POS scan resolves to.
//
// kind ITEM: `variant` is the exact variant whose barcode/SKU matched, or
// null when the code belonged to a simple product, which is itself the
// purchasable item. `numbers` is empty.
//
// kind VARIANT_SELECTION: the code was the parent of a product that has
// variants — a numbered shawl's collection label, or a supplier's one code
// for every size. There is nothing sellable to return — `variant` is null —
// and the cashier picks from `product.variants`. For a numbered product,
// `numbers` carries the same choice laid out by number (with each number's
// stock and its point on the photo); it is empty for an ordinary one.
export interface ProductLookupResult {
  kind: ProductLookupKind;
  product: Product;
  variant: Variant | null;
  numbers: ProductNumberOption[];
}

// POST /api/products/labels/printed — the products whose labels were just
// sent to the printer, and the timestamp now stamped on all of them.
export interface MarkLabelsPrintedResult {
  productIds: string[];
  labelsPrintedAt: string;
}
