import type { I18n } from "@/types/common";
import type { ChangeRequest } from "@/types/changeRequest";
import type { BarcodeSource } from "@/types/product";

// Global option value (e.g. Color -> "أحمر"), GET /api/variant-types.
export interface VariantOptionValue {
  id: string;
  variantTypeId: string;
  value: I18n;
  key: string;
  sortOrder: number;
  createdAt: string;
}

// Global variant type (e.g. Color, Size, Number) with its values, shared
// across all products (CLAUDE.md: "Number/الأرقام" is not special — it's a
// normal variant type). GET /api/variant-types.
export interface VariantType {
  id: string;
  name: I18n;
  slug: string;
  values: VariantOptionValue[];
  createdAt: string;
}

export interface ProductImageRef {
  id: string;
  url: string;
  mediumUrl: string;
  thumbnailUrl: string;
  sortOrder: number;
  isPrimary: boolean;
  // How light or dark the photograph is, 0–100, measured by sharp when it was
  // uploaded (spec.md "Numbered shawls"). What the automatic suggestion for
  // the numbers' colour is read from — a dark photo gets light markers — so
  // the shop is rarely asked to think about it. Null for a photo uploaded
  // before this was recorded, which simply keeps the shipped marker.
  brightness: number | null;
}

// A variant's resolved reference to a global option value (CLAUDE.md rule 2)
// — the value is looked up by id, never copied as text.
export interface VariantOptionValueRef {
  id: string;
  variantTypeId: string;
  value: I18n;
  key: string;
  // What this value means ON THIS PRODUCT (spec.md "Notes on a product's
  // options") — "طول البنطلون ٩٥ سم" against a pair of trousers' own S. Null
  // when nothing was written, which is the usual case. It travels with the
  // value reference rather than in a list of its own so that every screen
  // that already draws the value gets the note with it, and none of them can
  // quietly show notes for colours but not for numbers.
  note: I18n | null;
}

export interface Variant {
  id: string;
  variantNumber: number;
  name: I18n;
  sku: string;
  // Per-variant code — generated by us, or the supplier's own when
  // `barcodeSource` is SUPPLIER. Independent of the parent's: a parent may
  // carry one shared supplier code while its variants keep their own.
  barcode: string | null;
  barcodeSource: BarcodeSource;
  // Fallback rule (CLAUDE.md rule 3): null on the variant falls back to the
  // parent product; resolvedPrice/resolvedCost carry the already-resolved value.
  priceOverride: string | null;
  resolvedPrice: string;
  stock: number;
  isActive: boolean;
  // Numbered shawls (spec.md): point on the product image, percentage 0-100.
  // Null for ordinary (non-numbered) variants.
  imageX?: number | null;
  imageY?: number | null;
  images: ProductImageRef[];
  values: VariantOptionValueRef[];
  createdAt: string;
  updatedAt: string;
  // SENSITIVE (CLAUDE.md rule 19): Admin + Manager only — absent entirely
  // from Employee responses.
  cost?: string | null;
  resolvedCost?: string | null;
  // Gated changes waiting for an Admin on this variant — its price override
  // or its stock (spec.md "Employee change approvals"). Present on the
  // responses that could have filed one; empty otherwise.
  pendingChanges?: ChangeRequest[];
}
