-- CreateEnum
CREATE TYPE "LabelPrintMode" AS ENUM ('THERMAL', 'A4_GRID');

-- AlterTable
ALTER TABLE "Product" ADD COLUMN     "labelsPrintedAt" TIMESTAMP(3);

-- AlterTable
ALTER TABLE "Setting" ADD COLUMN     "labelColumns" INTEGER NOT NULL DEFAULT 3,
ADD COLUMN     "labelGapXMm" DOUBLE PRECISION NOT NULL DEFAULT 3,
ADD COLUMN     "labelGapYMm" DOUBLE PRECISION NOT NULL DEFAULT 3,
ADD COLUMN     "labelHeightMm" DOUBLE PRECISION NOT NULL DEFAULT 30,
ADD COLUMN     "labelPageMarginBottomMm" DOUBLE PRECISION NOT NULL DEFAULT 10,
ADD COLUMN     "labelPageMarginLeftMm" DOUBLE PRECISION NOT NULL DEFAULT 8,
ADD COLUMN     "labelPageMarginRightMm" DOUBLE PRECISION NOT NULL DEFAULT 8,
ADD COLUMN     "labelPageMarginTopMm" DOUBLE PRECISION NOT NULL DEFAULT 10,
ADD COLUMN     "labelPrintMode" "LabelPrintMode" NOT NULL DEFAULT 'THERMAL',
ADD COLUMN     "labelRows" INTEGER NOT NULL DEFAULT 8,
ADD COLUMN     "labelWidthMm" DOUBLE PRECISION NOT NULL DEFAULT 50;

-- CreateIndex
CREATE INDEX "Product_labelsPrintedAt_idx" ON "Product"("labelsPrintedAt");
