name: Deploy Backend

on:
  push:
    branches:
      - main
    paths:
      - "backend/**"

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy Backend to VPS
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.VPS_SSH_KEY }}
          port: ${{ secrets.VPS_PORT }}
          script: |
            export NVM_DIR="$HOME/.nvm"
            source "$NVM_DIR/nvm.sh"

            if [ ! -d "/root/organza-store" ]; then
              git clone git@github.com:suhaibbaba/organza-store.git /root/organza-store
            fi

            cd /root/organza-store
            git pull origin main

            cd backend
            npm install
            npm run build
            npx medusa migrations run

            pm2 describe medusa > /dev/null 2>&1 \
              && pm2 restart medusa \
              || pm2 start npm --name "medusa" -- run start

            pm2 save
